#!/bin/zsh

## overrides for processes that fon't like being redirected and you probably don't want to


less() {
    command less >${TTY} 2>&1 "$@"
}

mc() {
    command mc >${TTY} 2>&1 "$@"
}

## the working horse

forq() {
    # Sanity checks, is this qterminal, do we have qdbus and sed? #########################################
    # todo: maybe work away from sed
    if [[ -z "$QTERM_DBUS_SERVICE" ]]; then
        printf '\e[1;31mThis does not seem to be qterminal.\nRefusing action.\nGood bye.\e[0m\n'
        return 1
    fi
    local QDBUS=$(command -v qdbus)
    [[ -z "$QDBUS" ]] && QDBUS=$(command -v qdbus6)
    if [[ -z "$QDBUS" ]]; then
        printf '\e[1;31mCannot find qdbus or qdbus6\nGood bye.\e[0m\n'
        return 1
    fi
    if ! command -v sed >/dev/null 2>&1; then
        printf '\e[1;33mCannot find sed\n"forq list" will not work.\e[0m\n'
    fi

    # easter egg :) #######################################################################################
    if [[ "$1" == "bomb" ]]; then
        printf "\n\e[33;40m\e[0K
              \e[1;31m◉\e[0;33;40m\e[0K
       I'm sorry, Dave.\e[0K
  I'm afraid I can't do that.\e[0K
\e[0m\n\n"
        return 1
    fi
    #######################################################################################################

    # nb. that this is NOT the same as $$ which will be our parenting shell even on self-calling this function as fork
    # note to self, -d " " causes TTOU (or TTIN?)
    local this_pid && read this_pid junk </proc/self/stat

    # management #########################################################################################
    case "$1" in
        "close"|"kill")
        local what=$2
        [[ -n $what ]] && (( $what == $this_pid )) && unset what # in case the user issues the main PID as parameter
        if [[ -z $what ]]; then
            # return the output to avoid the forq'd off processes running into stdout errors
            # todo: figure a way to do this for forq'd of processes instead of the main shell
            exec 1>${TTY}
            exec 2>${TTY}
            unset qterm_forq_out
            unset qterm_forq_err
            [[ -z "$UN4Q_PAGER" ]] || PAGER="$UN4Q_PAGER"
            [[ -z "$UN4Q_GIT_PAGER" ]] || GIT_PAGER="$UN4Q_GIT_PAGER"
        else
            if [[ "$1" == "kill" ]]; then
                pkill -P $what
            elif [[ -d /proc/$what ]]; then
                printf "\e[1;31mPID $2 seems still running, closing the pty might cause it to error\nUse forq kill $2 to kill it\e[0m\n" >&2
                return 1
            fi
        fi
        $QDBUS $QTERM_DBUS_SERVICE /terminals/${what:-$this_pid}_stdout closeTerminal >/dev/null 2>&1
        local RET=$?
        $QDBUS $QTERM_DBUS_SERVICE /terminals/${what:-$this_pid}_stderr closeTerminal >/dev/null 2>&1
        local RET2=$?
        ((RET != 0)) && RET=$RET2
        ((RET != 0)) && printf "\e[1;31mThere's no pty for PID ${what:-$this_pid}\nTry 'forq list'\e[0m\n" >&2
        # … and re-activate the one currently in use
        $QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT activateTerminal
        return $RET
        ;;

        "list")
            while read pid; do
                local current="  "
                ((pid == this_pid)) && current="* "
                local cmdline="[finished]"
                [[ -e /proc/$pid/cmdline ]] && read cmdline < /proc/$pid/cmdline
                printf "${current}${pid}\t ${cmdline}\n" >&2
            # todo: replace sed with shell parsing
            done < <($QDBUS $QTERM_DBUS_SERVICE | sed -n 's/\/terminals\/\([0-9]*\)_std\(out\|err\)/\1/p')
            return 0
        ;;

        "pause")
            if [[ -n "$2" ]]; then
                # todo: this does not work, the subshell is blocked by the process we forked off and doesn't handle signals
                kill -SIGUSR1 $2
            else
                exec 1>${TTY}
                exec 2>${TTY}
            fi
            return 0
            ;;

        "resume")
            if [[ -n "$2" ]]; then
                # todo: see above… :(
                kill -SIGUSR2 $2
            elif [[ -n "${qterm_forq_out}" ]]; then
                exec 1>${qterm_forq_out}
                exec 2>${qterm_forq_err}
                return 0
            else
                printf "\e[31mI'm sorry, I don't know where to go.\e[0m\n"
                return 1
            fi
            ;;
        *)
        ;;
    esac

    #######################################################################################################

    # "job" is our internal command, otherwise figure what the user wants #################################
    if [[ "$1" != "job" ]]; then
        local direction=${FORQ_WHERE:-below}
        local qterm_cmd="__qterm_canvas"
        local stdout
        local stderr
        while (( $# > 0 )); do
            case "$1" in
                "help")
                printf 'Usage:
  · forq [aside|below|tab|window] [1|2|3|1+2] [command]
         1 and 2 refer to stdout (default) and stderr
  · forq off [1|2|3|1+2] command
         fork and redirect command into the main target
  · forq list|pause|resume
  · forq close [ID]

Try to not close a terminal with a running job.\n'
                return 1
                ;;
                "aside"|"below"|"tab"|"win"|"window"|"off") direction="$1" ;;
                "paged") qterm_cmd="less -R -B -f -" ;;
                1) stdout=true; stderr=false ;;
                2) stdout=false; stderr=true ;;
                3|"1+2") stdout=true; stderr=true ;;
                *) break ;;
            esac
            shift
        done
    fi
    #######################################################################################################

    # if the user tries "forq someprogram" fork that off here and return, the subshell will perform the relevant action
    # this allows us to use the PID as dbus ID for the subterminal
    if (( $# > 0 )) && [[ "$1" != "job" ]]; then
        if [[ -z $stdout ]]; then
            local redir=${FORQ_JOB_REDIRECT:-3}
            ((redir & 1)) && stdout=true || stdout=false
            ((redir & 2)) && stderr=true || stderr=false
        fi

#        setopt LOCAL_OPTIONS NO_NOTIFY NO_MONITOR
        forq job ${@} &
        return 0
    fi
    #######################################################################################################
    if [[ -z $stdout ]] && (( $# == 0 )); then
        local redir=${FORQ_REDIRECT:-1}
        ((redir & 1)) && stdout=true || stdout=false
        ((redir & 2)) && stderr=true || stderr=false
    fi

    # make a new terminal. "__qterm_canvas" is a special command that will create a passive, output-only terminal
    local dbus_id
    local stdPty
    local stdoPty
    local stdePty
    $stdout && dbus_id=${this_pid}_stdout || dbus_id=${this_pid}_stderr

    if $QDBUS $QTERM_DBUS_SERVICE | grep -q "/terminals/${this_pid}_"; then
        printf "\e[1;31mYou already have a terminal for ${this_pid}\e[0m\n"
        return 1
    fi

    case "$direction" in
    "aside")
        stdPty=$($QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT splitHorizontal $dbus_id "$qterm_cmd" "$PWD" 50)
        ;;
    "below")
        stdPty=$($QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT splitVertical $dbus_id "$qterm_cmd" "$PWD" 75)
        ;;
    "tab")
        stdPty=$($QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT newTab $dbus_id "$qterm_cmd" "$PWD")
        ;;
    "win"|"window")
        stdPty=$($QDBUS $QTERM_DBUS_SERVICE / newWindow $dbus_id "$qterm_cmd" "$PWD" "" "")
        ;;
    "off")
        [[ -z $qterm_forq_out ]] && printf '\e[1;31mThere seems no main redirection to use?\e[0m\n' && return 1
        stdoPty=$qterm_forq_out
        stdePty=$qterm_forq_err
        [[ -n "$stdoPty" ]] && stdPty=$stdoPty || stdPty=s$tdePty
        ;;
    *)
        printf "\e[1;31mI don't know where $direction is…\e[0m\n"
        return 1
        ;;
    esac

    $stdout && stdoPty=$stdPty || stdePty=$stdPty

    # … and re-activate the one the user can still type into
    $QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT activateTerminal
    #######################################################################################################

    [[ -z "$TTY" ]] && TTY=$(tty) # bash doesn't set that global variable

    if [[ "$1" == "job" ]]; then
    # we also need to actually run what the user wanted
        shift
        if [[ -z $stdePty ]]; then
            if $stderr; then
                stdePty=$stdPty
            else
                local SPLIT=splitVertical
                local PRECENT=25
                if [[ "$direction" == "below" ]]; then
                    SPLIT=splitHorizontal
                    PRECENT=50
                fi
                stdePty=$($QDBUS $QTERM_DBUS_SERVICE /terminals/${dbus_id} $SPLIT ${this_pid}_stderr "$qterm_cmd" "$PWD" $PRECENT)
            fi
        fi

    # the commented stuff is failed attempts at signal handling :(
#        trap "echo foo >&2; tty; exec 1>${TTY}; exec 2>${TTY}" USR1
#        trap "$stdout && exec 1>${stdoPty}; $stderr && exec 2>${stdoPty}" USR2
#        trap "echo SOS" PIPE
        # The idea was to auto-foreground jobs if they want something, but
        # 1. seems not possible, 2. is probably too invasive anyway
#        setopt monitor
#        trap "echo TTOU >&2" TTOU
#        trap "echo TTIN >&2" TTIN
        # this allows ctrl+z to re-background jobs (eg. after fg them to provide sudo input) w/o implicitly stopping them
        trap '' TSTP

        # we use a fifo se we can use a non-blocking read to wait for the payload and handle signals as they come
#        mkdir -p /var/run/user/$UID/forq
#        local fifo=/var/run/user/$UID/forq/$this_pid
#        mkfifo $fifo


        [[ "$direction" == "tab" ]] && $QDBUS $QTERM_DBUS_SERVICE /tabs/$dbus_id setLabel "$this_pid $@"
        $stdout && [[ -n $stdoPty ]] && exec 1>${stdoPty}
        [[ -n $stdePty ]] && exec 2>${stdePty}

#        (
            # pipe this through a pointless tee to contain EIO of the child processes
            # todo: maybe tee into a tmpfile so the user can check the job output ex post?
            # probablem is that the job won't understand that it's writing to a PTY, breaks eg. colors
#            eval "$@" | tee --output-error=warn /dev/null
            eval "$@"
            local ret=$?
            if (( $ret == 127)); then # 127 == failed to start
                $QDBUS $QTERM_DBUS_SERVICE /terminals/${this_pid}_stdout closeTerminal > /dev/null 2>&1
                $QDBUS $QTERM_DBUS_SERVICE /terminals/${this_pid}_stderr closeTerminal > /dev/null 2>&1
                $QDBUS $QTERM_DBUS_SERVICE $QTERM_DBUS_OBJECT activateTerminal
            else
                local smiley="(:"
                (($ret != 0)) && smiley="):"
                [[ "$direction" == "tab" ]] && $QDBUS $QTERM_DBUS_SERVICE /tabs/$dbus_id setLabel "$smiley $this_pid $@"
                # todo, bell doesn't seem handled
                printf '\a' >${TTY}; sleep 0.5; printf '\a' >${TTY} # dun-dun
            fi
#            echo $ret > $fifo
#        ) &
#        echo $! >&2
#        local result; read result < $fifo
#        rm $fifo
        echo $result >&2
    else
    # otherwise redirect the main shell and record that in a global variable for pause/resume
        $stderr && [[ -z $stdePty ]] && stdePty=$stdoPty
        qterm_forq_out=${stdoPty}
        qterm_forq_err=${stdePty:-$TTY}
        $stdout && [[ -n $stdoPty ]] && exec 1>${stdoPty}
        $stderr && [[ -n $stdePty ]] && exec 2>${stdePty}
        [[ -n "$PAGER" ]] && UN4Q_PAGER="$PAGER"
        PAGER="${PAGER:-less} >${TTY} 2>&1"
        if [[ -n "$GIT_PAGER" ]]; then
            UN4Q_GIT_PAGER="$GIT_PAGER"
            GIT_PAGER="$GIT_PAGER >${TTY} 2>&1"
        fi
    fi
}

# autocompletion ######################################################################################################

if [[ -n "$ZSH_VERSION" ]]; then
_forq() {
    case "${words[2]}" in
        "kill"|"close")
            local QDBUS=$(command -v qdbus)
            [[ -z "$QDBUS" ]] && QDBUS=$(command -v qdbus6)
            local JOBS=($($QDBUS $QTERM_DBUS_SERVICE | sed -n 's/\/terminals\/\([0-9]*\)_std\(out\|err\)/\1/p'))
            compadd "${JOBS[@]}"
            return
        ;;
        *)
        ;;
    esac
    local COMPREPLY=("aside" "below" "tab" "win" "window" "list" "close" "kill" "help" "pause" "resume" "1" "2" "1+2" "off")
    compadd "${COMPREPLY[@]}"
    return
}
compdef _forq forq
fi

if [[ -n "$BASH_VERSION" ]]; then
_forq() {
case "${COMP_WORDS[1]}" in
        "kill"|"close")
            local QDBUS=$(command -v qdbus)
            [[ -z "$QDBUS" ]] && QDBUS=$(command -v qdbus6)
            COMPREPLY=($($QDBUS $QTERM_DBUS_SERVICE | sed -n 's/\/terminals\/\([0-9]*\)_std\(out\|err\)/\1/p'))
            return 0
        ;;
        *)
        ;;
    esac
    COMPREPLY=($(compgen -W "aside below tab win window list close kill help pause resume 1 2 1+2 off" -- ${COMP_WORDS[$COMP_CWORD]}))
    return 0
}
complete -F _forq forq
complete -F _forq 4q
fi

alias 4q=forq